"""dawnr_interp.sae: the dictionary-learning recipe itself (arXiv:2309.08600; see
dawnr_interp/sae.py's module docstring for exactly what is and is not from the
paper). What must hold: the config rejects nonsensical widths, tied encode/decode
agree with the paper's equations, the dictionary starts and stays unit-norm per row,
and training on data actually generated by a small sparse dictionary drives
reconstruction error down -- the property Wright & Ma (2022, cited by the paper)
gives a reason to expect. Needs torch; CPU only, seconds.
"""
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import torch  # noqa: E402

from dawnr_interp.sae import SAEConfig, SparseAutoencoder, dead_features, train_sae  # noqa: E402


class SAEConfigTest(unittest.TestCase):
    def test_d_hidden_is_expansion_times_d_in(self):
        self.assertEqual(SAEConfig(d_in=4, expansion=3).d_hidden, 12)

    def test_rejects_nonpositive_d_in(self):
        with self.assertRaises(ValueError):
            SAEConfig(d_in=0)

    def test_rejects_nonpositive_expansion(self):
        with self.assertRaises(ValueError):
            SAEConfig(d_in=4, expansion=0)

    def test_rejects_negative_l1(self):
        with self.assertRaises(ValueError):
            SAEConfig(d_in=4, l1_coefficient=-0.1)


class SparseAutoencoderTest(unittest.TestCase):
    def setUp(self):
        torch.manual_seed(0)
        self.config = SAEConfig(d_in=6, expansion=3, l1_coefficient=1e-3)
        self.sae = SparseAutoencoder(self.config)

    def test_forward_shapes_and_nonnegative_code(self):
        x = torch.randn(5, 6)
        recon, code = self.sae(x)
        self.assertEqual(recon.shape, (5, 6))
        self.assertEqual(code.shape, (5, 18))
        self.assertTrue(torch.all(code >= 0))

    def test_decode_is_encoder_weight_transposed(self):
        # x_hat = M^T code (eq. 2-3): decoding the identity-like standard basis
        # rows of a d_hidden-sized code should return exactly the dictionary rows.
        code = torch.eye(self.config.d_hidden)
        recon = self.sae.decode(code)
        torch.testing.assert_close(recon, self.sae.encoder.weight)

    def test_dictionary_rows_start_unit_norm(self):
        norms = self.sae.encoder.weight.norm(dim=1)
        torch.testing.assert_close(norms, torch.ones(self.config.d_hidden), atol=1e-5, rtol=0)

    def test_normalize_decoder_handles_a_zeroed_row(self):
        with torch.no_grad():
            self.sae.encoder.weight[0].zero_()
        self.sae.normalize_decoder_()  # must not divide by zero into nan/inf
        self.assertTrue(torch.isfinite(self.sae.encoder.weight).all())

    def test_loss_rejects_mismatched_width(self):
        with self.assertRaises(ValueError):
            self.sae.loss(torch.randn(3, 7))

    def test_loss_components_are_nonnegative(self):
        loss, parts = self.sae.loss(torch.randn(4, 6), return_components=True)
        self.assertGreaterEqual(float(loss.detach()), 0.0)
        self.assertGreaterEqual(float(parts["reconstruction"]), 0.0)
        self.assertGreaterEqual(float(parts["sparsity_l1"]), 0.0)
        self.assertGreaterEqual(float(parts["l0"]), 0.0)
        self.assertLessEqual(float(parts["l0"]), self.config.d_hidden)


class DeadFeaturesTest(unittest.TestCase):
    def test_finds_the_column_that_never_fires(self):
        code = torch.tensor([[0.0, 1.0, 0.0],
                             [0.0, 0.0, 0.3],
                             [0.0, 2.0, 0.0]])
        torch.testing.assert_close(dead_features(code), torch.tensor([True, False, False]))

    def test_rejects_non_matrix_input(self):
        with self.assertRaises(ValueError):
            dead_features(torch.zeros(5))


class TrainSAETest(unittest.TestCase):
    def test_rejects_mismatched_width(self):
        sae = SparseAutoencoder(SAEConfig(d_in=6, expansion=2))
        with self.assertRaises(ValueError):
            train_sae(sae, torch.randn(10, 5), steps=1)

    def test_rejects_empty_activations(self):
        sae = SparseAutoencoder(SAEConfig(d_in=6, expansion=2))
        with self.assertRaises(ValueError):
            train_sae(sae, torch.empty(0, 6), steps=1)

    def test_history_has_one_record_per_step_and_shrinking_loss(self):
        torch.manual_seed(1)
        sae = SparseAutoencoder(SAEConfig(d_in=6, expansion=4, l1_coefficient=1e-4))
        activations = torch.randn(64, 6)
        history = train_sae(sae, activations, steps=25, batch_size=16, lr=1e-2, seed=0)
        self.assertEqual(len(history), 25)
        self.assertLess(history[-1]["loss"], history[0]["loss"])

    def test_recovers_a_small_planted_dictionary(self):
        """Data generated as sparse combinations of a small ground-truth dictionary
        (Olshausen & Field's own setup, section 2's cited motivation): training
        should pull mean squared reconstruction error well below the untrained
        starting point, the one property this whole recipe exists to buy."""
        torch.manual_seed(2)
        d_in, k, n = 12, 5, 512
        true_dict = torch.nn.functional.normalize(torch.randn(k, d_in), dim=1)
        active = torch.rand(n, k) < 0.2                                   # sparse support
        magnitude = torch.rand(n, k) * active
        activations = magnitude @ true_dict

        sae = SparseAutoencoder(SAEConfig(d_in=d_in, expansion=4, l1_coefficient=3e-3))
        with torch.no_grad():
            initial_mse = (activations - sae(activations)[0]).pow(2).mean().item()
        train_sae(sae, activations, steps=300, batch_size=128, lr=3e-3, seed=0)
        with torch.no_grad():
            final_mse = (activations - sae(activations)[0]).pow(2).mean().item()

        self.assertLess(final_mse, initial_mse * 0.2)


if __name__ == "__main__":
    unittest.main()
